### ISSUE TITLE
global path planner failed！！！

### ISSUE THREAD

**Issue by adl-123** [dfl-rlab/dddmr_navigation#8]
When I am performing global path planning, I often encounter the problem that the robot cannot accurately reach the target point nearby. The rotation controller keeps working, or DWA is blocked and cannot be stopped by pressing ctrl+c. Has the author encountered this problem before? @tsengapola

**Comment by tsengapola** [comment]
It means there is obstacle in the inscribed_radius, so the path planning rejects your path and controller refuse to move the robot. 
The default value in the config is 0.5 meter.

https://github.com/dfl-rlab/dddmr_navigation/blob/64c625e6a3ea802c091734243d9ce1426bade5c8/src/dddmr_p2p_move_base/config/p2p_move_base_localization.yaml#L254

https://github.com/dfl-rlab/dddmr_navigation/blob/64c625e6a3ea802c091734243d9ce1426bade5c8/src/dddmr_p2p_move_base/config/p2p_move_base_localization.yaml#L291

If your robot is 0.6 meter long, then you can set inscribed_radius to 0.3 or a little bit larger say 0.32.


For ctrl+c issue, I think the log was printing so fast that it became difficult to kill. I will fix it by throttling the log.
Thank you very much for reporting this issue!!!

**Comment by adl-123** [comment]
Thank you for your answer. Now I have another question. I have noticed that when I perform multiple planning operations, the planning speed becomes slower and slower, and sometimes no path can be planned. It seems that the planning has already succeeded, but the planning process hasn't ended yet, and the log is still being output. What could be the problem?

**Comment by adl-123** [comment]
https://youtu.be/Ee0L__NJibs

**Comment by adl-123** [comment]
@tsengapola Your modification is excellent. It seems that the problem has been solved. I will continue to use it in the future. Thank you!

<img width="1296" height="588" alt="Image" src="https://github.com/user-attachments/assets/100cc4a1-9425-4e5e-b1aa-501ac0ce4b0f" />

**Comment by adl-123** [comment]
@tsengapola I found another issue. I added a lidar as a sensor, but sometimes the global planning directly passes through obstacles without generating obstacle avoidance

<img width="994" height="865" alt="Image" src="https://github.com/user-attachments/assets/105f09c3-17cb-4170-b145-002344e37493" />

video:
https://youtu.be/SXTjPLyy81k

**Comment by adl-123** [comment]
https://youtu.be/09ia_vKVB88
This way, the problem becomes more apparent

**Comment by adl-123** [comment]
@tsengapola 
Watch this video：https://youtu.be/I-t-78cR94M

**Comment by adl-123** [comment]
@tsengapola
Watch this video：
https://github.com/user-attachments/assets/998a9a8b-05d1-4263-b570-9114d73f06f6

**Comment by tsengapola** [comment]
Thank you for the video, it looks strange because even potential does not work.
I need couple days to write some tests to check.

**Comment by adl-123** [comment]
@tsengapola  There are still such issues
<img width="1105" height="697" alt="Image" src="https://github.com/user-attachments/assets/c108b06f-bcdf-45c1-925f-8830dbb17514" />

**Comment by adl-123** [comment]
@tsengapola OK, maybe replacing "lego loam" with "lio sam" might not be appropriate, but I don't think it should cause any issues with path planning. Could you help me analyze the root cause of this problem first?After modifying get_plan and the parameters, the problem still persists.

https://youtu.be/XnvSmS1a8_4

<img width="458" height="147" alt="Image" src="https://github.com/user-attachments/assets/44e38a4c-6ce1-4d52-b275-7f96122c7990" />
<img width="396" height="132" alt="Image" src="https://github.com/user-attachments/assets/465f16a9-5c38-45e7-b698-89eb4a896f90" />

**Comment by tsengapola** [comment]
I identified and can reproduce the issue.

Basically the issue is that when A* doing the expanding, we do not check line-of-sight because we want to save computation time. However, when expanding radius>2*inscribed_radius, this issue will occur.

https://github.com/dfl-rlab/dddmr_navigation/blob/8d102bc3782d5305472f052b945ceebf6e9e3269/src/dddmr_global_planner/src/a_star_on_pc.cpp#L198

If you change above line from 1.0 to 0.5, I think the path will be correct. Because 0.5<2*your_inscrebed_radius. Make sure your ground voxel size is smaller than 0.5 m.

But reducing search radius is not a good solution. We are working on an better solution that we will check line-of-sight when expanding. In addition, I will parameterize this value for user to setup. The new release will require couple days.

**Comment by adl-123** [comment]
You are right, the problem indeed lies here. Looking forward to your new release, thank you for your efforts

**Comment by adl-123** [comment]
https://youtu.be/fQIXKv6Gmfw
Hello, I tried your latest code. In my case, is it because some parameters are not set correctly?
@tsengapola When I increase the perception_window_size in perception_3d_global, such a warning appears, causing the path planning to be delayed.

<img width="1197" height="859" alt="Image" src="https://github.com/user-attachments/assets/e02ac184-e309-4756-8df5-7fd0a0c13763" />

**Comment by tsengapola** [comment]
Change look ahead distance to 10.0 meters enable the robot to plan earlier when seeing the wall. It should solve the issue.

https://github.com/dfl-rlab/dddmr_navigation/blob/eb691285a584c0a07cfac0ae0b52da4a84b21cb3/src/dddmr_p2p_move_base/config/p2p_move_base_localization.yaml#L338

Setting perception window size larger will include a lot of point cloud for marking and clearing, result in slow speed. You can set it to 5-10 meters, should be fine once look ahead become larger.
But I still would like to know what is your point cloud size:
```
ros2 topic bw non_ground_cloud
```

**Comment by tsengapola** [comment]
It looks like look_ahead_distance is still 2.0 meters in your video. Because the only modify a short pah in the green path.
Do you see logs something like this:
```

[global_planner_node-2] [INFO] [1756372591.313455761] [dynamic_window_aware_global_planner]: look_ahead_distance: 100.00
[global_planner_node-2] [INFO] [1756372591.313558624] [dynamic_window_aware_global_planner]: recompute_frequency: 10.00

```

**Comment by adl-123** [comment]
<img width="1267" height="777" alt="Image" src="https://github.com/user-attachments/assets/925ed2a5-ea3f-4bc8-80b9-36ab8e33b4c4" />

<img width="350" height="156" alt="Image" src="https://github.com/user-attachments/assets/8ffd0d01-1a48-48e5-b05d-ffed7da73e1f" />
Do you mean we should change it to 10.0 here as well?
What I mean is, have you noticed that at the end of the video, the global path directly goes through the obstacle without any error, and then enters wait

**Comment by adl-123** [comment]
I used `colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release`, applied the `issue8` branch, and changed `look_ahead_distance` to 10.0. However, this scenario still fails to pass
@tsengapola 
https://github.com/user-attachments/assets/e514d1ca-1041-4c2c-acf5-ab1c712aba38

**Comment by adl-123** [comment]
https://github.com/user-attachments/assets/0209dbf8-9b54-4793-96c7-ee97bac4b3ba

**Comment by tsengapola** [comment]
can you show me
```
git log
```

**Comment by adl-123** [comment]
<img width="644" height="779" alt="Image" src="https://github.com/user-attachments/assets/37aad7ec-fa4a-415d-badd-19d53d15a14c" />

**Comment by adl-123** [comment]
[20250827.zip](https://github.com/user-attachments/files/22037339/20250827.zip)

**Comment by tsengapola** [comment]
Can you also provide the point cloud in video for around 30 seconds. Also what is your ground voxel size?

https://github.com/user-attachments/assets/6d237445-c6db-40a8-9eb9-6414bcc3172c

**Comment by adl-123** [comment]
<img width="528" height="156" alt="Image" src="https://github.com/user-attachments/assets/c6aedf47-e2b6-40b6-8cf3-a16c8d85b61e" />

[dddmr.db3.zip](https://github.com/user-attachments/files/22039581/dddmr.db3.zip)

tf in rosbag,I've noticed a slight issue with my self-positioning. The z-value seems to be getting lower and lower. Will this affect the planning? I observed that the problematic wall doesn't appear as dark in color in dGraph

**Comment by tsengapola** [comment]
![Image](https://github.com/user-attachments/assets/4783580a-426a-448c-b407-ff7f67b83063)

In theory, when the position is correct, it means you are minimize the delta Z, so the value of dGraph is somehow the distance of xy plane.

Regarding the z value issue, the robot should get close to the correct ground so that it can deal with multi-floor problem:
From the picture, projection to the ground is based on the delta Z, if the z value is incorrect, the selection for the ground point will be wrong.

Regarding, the z removal for the dGraph value, I think it should be no harm to remove z, I will work on a new commit for it.
